apiVersion: apps/v1
kind: Deployment
metadata:
  name: crisp-deploy
  namespace: crisp
  labels:
    app: crisp-app
  annotations:
spec:
  selector:
    matchLabels:
      app: crisp-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crisp-app
    spec:
      containers:
      - name: crisp-app
        # image: 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: example-config