apiVersion: apps/v1
kind: Deployment
metadata:
  name: crisp-deploy
  namespace: crisp
  labels:
    app: crisp-app
  annotations:
spec:
  selector:
    matchLabels:
      app: crisp-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crisp-app
    spec:
      containers:
      - name: crisp-app
        image: us-central1-docker.pkg.dev/crisp-service/crisp-artifacts/crisp-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
