apiVersion: v1
kind: Service
metadata:
  name: crisp-lb-service
  namespace: example
  labels:
    app: crisp-app
spec:
  type: LoadBalancer
  selector:
    app: crisp-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000